language: android
android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-24.0.3
    - android-24

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19
    # Specify at least one system image, if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-armeabi-v7a-android-17
script:
    - chmod +x ./gradlew